# Generated by Django 3.1.5 on 2021-06-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210609_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='Data',
        ),
    ]
