# Generated by Django 3.1.5 on 2021-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('fees', models.IntegerField()),
                ('number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
